### ISSUE TITLE
Rename pretty much all `id` parameters

### ISSUE THREAD

**Issue by dabrahams** [val-lang/val#179]
For example, in this method from `ConstraintGenerator`:

```swift
  private mutating func visit(
    functionCall id: NodeID<FunctionCallExpr>,
    using checker: inout TypeChecker
  ) -> AnyType {
```

"id" is about the least descriptive name one could think of, and when you look at the body of this function it's full of references to this thing that you can't tell what it is so individual statements look like operations on some ID of unknown significance.  The most descriptive thing I could think of would be `visitedCall` but I'd be happy with anything that makes its role clear at the use site.

**Comment by kyouko-taiga** [comment]
Issue has been fixed.
