### ISSUE TITLE
Child diagnostics don't seem to get reported

### ISSUE THREAD

**Issue by dabrahams** [val-lang/val#208]
If you look at the last commit on the [child-diagnostic-reporting-bug tag](https://github.com/val-lang/val/tree/child-diagnostic-reporting-bug), you can see an attempt to demonstrate.  All I see when the test fails is "unexpected diagnostic"

**Comment by kyouko-taiga** [comment]
Child diagnostics are not taken into account when test annotations are handled. They are only reported by the CLI at the moment.

**Comment by kyouko-taiga** [comment]
I guess we can close this issue. Feel free to re-open if something should still be done.
