### ISSUE TITLE
SourceLocation vs SourcePosition

### ISSUE THREAD

**Issue by dabrahams** [val-lang/val#225]
This is really trivial, but it came up for me so here it is: `SourceLocation` evokes a directory/path, while `SourcePosition` does not.  We don't talk about the position of files.  Maybe rename stuff at some point. FWIW.

**Comment by kyouko-taiga** [comment]
It's a departure from Clang and swiftc, but it sounds totally reasonable. I'll make the change.

**Comment by dabrahams** [comment]
Maybe hold off for a bit; I'm currently working in that area.  Or, I could make it?
