### ISSUE TITLE
Archive stale branches and move rewrite to main?

### ISSUE THREAD

**Issue by dabrahams** [val-lang/val#23]
Instructions for archiving are [here](https://gist.github.com/zkiraly/c378a1a43d8be9c9a8f9?permalink_comment_id=3131614)

**Comment by dabrahams** [comment]
If we at least change the primary branch to `rewrite` then I think commit messages like “fixes #21" will actually close issues when merged.

**Comment by kyouko-taiga** [comment]
- Archived stale branches
- Renamed the former `main` branch to `legacy`
- Swapped `main` and `rewrite`
