### ISSUE TITLE
Windows CI is broken

### ISSUE THREAD

**Issue by dabrahams** [val-lang/val#236]

**Comment by compnerd** [comment]
Bumped the Windows CI to use 5.8 in the hopes that it will alleviate the flakiness.  Let's monitor and see what the best path forward is.  If it is still flakey, we may need to enable more tracing to figure out what is going on.

**Comment by dabrahams** [comment]
We are having successful builds on Windows; should we close this @compnerd ?

**Comment by compnerd** [comment]
@dabrahams I think so!  Thanks
