### ISSUE TITLE
builtinDecl needs more explanation

### ISSUE THREAD

**Issue by dabrahams** [val-lang/val#240]
```swift
    /// The node representing all built-in declarations.
    public var builtinDecl: NodeID<BuiltinDecl> { NodeID(rawValue: 0) }
```

The same single node for all built-in declarations?  Or is this the Builtin module?

**Comment by kyouko-taiga** [comment]
Fixed by 6405da003c1e536ad3235e0fab887479cf57e948.

We could perhaps eliminate this ID if `DeclRef` had a third case for references to built-in declarations, rather than using `.direct(AnyDeclID(program.ast.builtinDecl))`.
