### ISSUE TITLE
Cannot declare mutating postfix `++` operator

### ISSUE THREAD

**Issue by lucteo** [val-lang/val#277]
The following Val code:
```
  public mutating fun postfix++ () -> Self {
    self.copy()
  }
```

produces the following error:
```
FrontEnd/AST+Extensions.swift:20: Fatal error: Error parsing the core module:
The operation couldn’t be completed. (Core.Diagnostics error 1.)
```

Removing the `mutating` keyword makes the code compile properly.

**Comment by kyouko-taiga** [comment]
`mutating` is not a keyword in Val. You want:
```swift
public fun postfix++ () inout -> Self { ... }
```

**Comment by kyouko-taiga** [comment]
Note that we should probably not have postfix/infix increment/decrement: https://github.com/apple/swift-evolution/blob/main/proposals/0004-remove-pre-post-inc-decrement.md

**Comment by lucteo** [comment]
OK. Makes sense.
It would be nice to improve the error message, but we can do that later :)

Does this mean that we don't have any postfix operators in Val?

**Comment by kyouko-taiga** [comment]
If I'm not mistaken, in the standard library, only `Optional<T>` will have a postfix `!`. But that may evolve as we develop this library.
