### ISSUE TITLE
Better diagnostics w.r.t "unexpected declaration"

### ISSUE THREAD

**Issue by lucteo** [val-lang/val#282]
In many places the current version of the compiler has a fallback case that is implemented in terms of `unreachable("unexpected declaration")`

This makes the process of writing compilable programs harder.

We need to report the location of the AST node and its type.

**Comment by lucteo** [comment]
@kyouko-taiga : I can take care of this one, unless you want to take it. I got frustrated by this several times :)

**Comment by kyouko-taiga** [comment]
Would be nice if you could take care of it =)

**Comment by lucteo** [comment]
Fixing with #303
