### ISSUE TITLE
Downcast for TypedNode

### ISSUE THREAD

**Issue by dabrahams** [val-lang/val#289]
We have a lot of code like this: 

```swift
  func cxx(topLevel src: AnyDeclID.TypedNode) -> CXXTopLevelDecl {
    switch src.kind {
    case FunctionDecl.self:
      return cxx(function: FunctionDecl.Typed(src)!)
    case ProductTypeDecl.self:
      return cxx(type: ProductTypeDecl.Typed(src)!)
    default:
      unreachable("unexpected declaration")
    }
  }
```

It makes me think we can do better, e.g.

```swift
  func cxx(topLevel src: AnyDeclID.TypedNode) -> CXXTopLevelDecl {
    switch src.downcast() {
    case let f as FunctionDecl.Typed: return cxx(function: f)
    case let p as ProductTypeDecl.Typed: return cxx(type: p)
    default:
      unreachable("unexpected declaration")
    }
  }
```

I haven't thought about exactly what code would be necessary to make this work, but obviously a subtype relationship between the result of `downcast()` and all the typed nodes would be required.  The next question is whether the explicit `.downcast()` call should even be needed.  Maybe we can take care of always doing that when we create a `TypedNode`…

**Comment by dabrahams** [comment]
> The alternative would significantly change the internal representation of a typed erased ID

I imagined something like that would probably be necessary.  I don't know what to do about your debugging issue.  IMO readability of source code outweighs almost everything, but YMMV.

**Comment by kyouko-taiga** [comment]
No longer relevant.
