### ISSUE TITLE
Rename TypeChecker.decl

### ISSUE THREAD

**Issue by kyouko-taiga** [val-lang/val#299]
> I think it would be cleared up if the label were not `named:` but `ifNamed:`

I think `ifNamed` isn't a perfect fit. `checker.decl(d, named: n)` is returning:
- `d` if it's name is `n`; or
- `m` if `d` is a method declaration and `m` is an implementation/clause/variant whose name is `n`; or
- `nil` otherwise.

Perhaps the name of the method itself should be changed.

> renamed lookup to something that describes what it actually returns.

I am torn here. I think there's value of having all lookup methods share a common prefix, because it helps identifying that they are related. I'm trying to build a vocabulary of the kind of queries that are done during type checking. "Lookup" is one of them.

_Originally posted by @kyouko-taiga in https://github.com/val-lang/val/pull/280#discussion_r1092660397_

**Comment by dabrahams** [comment]
`ifHasName`?

**Comment by kyouko-taiga** [comment]
Still not fully satisfactory IMO. I'd like the name of the method and/or its labels to reflect the fact that it may be returning something other than `d`.

**Comment by dabrahams** [comment]
`checker.decl(in: d, named: n)` is the best I can do.

**Comment by kyouko-taiga** [comment]
LGTM
