### ISSUE TITLE
Diagnostics in test failures don't have the right format.

### ISSUE THREAD

**Issue by dabrahams** [val-lang/val#326]
For example, running the tests, I got:

/Users/dave/src/val/Sources/Core/Dianostics.swift:45: error: -[ValCommandTests.ValCommandTests testTypeCheckFailure] : failed: caught error: "file:///Users/dave/src/val/.build/arm64-apple-macosx/debug/Val_ValCommandTests.bundle/Inputs/Failure.val:2:11: error: undefined name 'foo' in this scope"

`/Users/dave/src/val/Sources/Core/Dianostics.swift:45: error:` is parsed fine by my IDE<i>macs</i>, but we need a newline just after the open quotation mark and we need to convert the URL back into a file path.

**Comment by kyouko-taiga** [comment]
So, I think that's because you're throwing a diagnostic log from some `XCTest` method. Diagnostics should be reported with `XCTest.report` to get the nicer output.

**Comment by dabrahams** [comment]
On Feb 3, 2023, at 6:26 PM, Dimi Racordon ***@***.***> wrote:



I think that's because you're throwing a diagnostic log from some XCTest method. Diagnostics should be reported with XCTest.report to get the nicer output.

The testing system should be set up so failures always come out with nice, readable output regardless of whether somebody explicitly calls XCTest.report.

It is, after all, a system for diagnosing mistakes.

**Comment by kyouko-taiga** [comment]
I failed to find a way to change the location XCTest uses to report uncaught exceptions (or any XCTAssert failure) without using `XCTest.report`. It seems you can't workaround the framework wanting a StaticString otherwise, which you can't build at runtime. Can't say with 100% certitude that `XCTest.report` is the only way, but like ... 99.9%.

We may be able to customize/subclass `XCTest` to catch `Diagnostics` error and call `XCTest.report` but I don't want to take on this fight myself.

**Comment by dabrahams** [comment]
_Something_ is generating the textual representation that appears in quotes.  Seems to me all we need to do is begin that generated text with a newline.

**Comment by kyouko-taiga** [comment]
I strongly suspect this something is `SourceRange.description`. If so, it's not a good solution to add a newline.

**Comment by dabrahams** [comment]
That's just part of Diagnostic.description, for which a leading newline is a good idea.

**Comment by kyouko-taiga** [comment]
I disagree:
1. This newline is not necessary if you just want to print a diagnostic;
2. It sounds like a hack to make the output easier to parse. We shouldn't write our text descriptions to deal with the whims of XCTest
3. Just focusing on improving the textual output will break Xcode integration.

**Comment by kyouko-taiga** [comment]
I think the solution is to build a mini test framework inside of XCTest. That's what `AnnotatedTestFile.swift` is.

XCTest might be the least portable thing in the Swift ecosystem, so if we want to get something more powerful we might have to create a test case generator to bypass test discovery (which is seriously crippled on non-apple platforms) and the shenanigans required to call `XCTest.report`.

**Comment by dabrahams** [comment]
On Feb 7, 2023, at 2:11 PM, Dimi Racordon ***@***.***> wrote:


  1.  This newline is not necessary if you just want to print a diagnostic;

It’s not necessary, but it's ALWAYS better for me.  I don’t have to jump to it if I don’t want to, but at least I can.

  1.  It sounds like a hack to make the output easier to parse.

It is exactly that.  Or, it’s a hack to make compiler development easier.

  1.  We shouldn't write our text descriptions to deal with the whims of XCTest

Has nothing to do with XCTest, this is for Emacs.

  1.  Just focusing on improving the textual output will break Xcode integration.

I don’t see how.  Xcode integration doesn’t use description directly does it?


–


Dave Abrahams  |  STLab  |  Adobe  |  C 617 501 9014  |  ***@***.***

**Comment by kyouko-taiga** [comment]
Xcode integration reads the path in the XCTIssue passed to `XCTest.report`. That's how I can get Val errors get reported in a Val file. Any other approach reports the error at the point where `XCTAssert` is called or where an exception is thrown.

**Comment by dabrahams** [comment]
On Feb 7, 2023, at 2:11 PM, Dimi Racordon ***@***.***> wrote:


  1.  This newline is not necessary if you just want to print a diagnostic;

It’s not necessary, but it's ALWAYS better for me.  I don’t have to jump to it if I don’t want to, but at least I can.

  1.  It sounds like a hack to make the output easier to parse.

It is exactly that.  Or, it’s a hack to make compiler development easier.

  1.  We shouldn't write our text descriptions to deal with the whims of XCTest

Has nothing to do with XCTest, this is for Emacs.

  1.  Just focusing on improving the textual output will break Xcode integration.

I don’t see how.  Xcode integration doesn’t use description directly does it?

**Comment by dabrahams** [comment]
On Feb 7, 2023, at 2:34 PM, Dimi Racordon ***@***.***> wrote:



Xcode integration reads the path in the XCTIssue passed to XCTest.report.

In that case I don’t understand the objection.   We can pass anything we want to XCTest.report, right?

The only thing Custom(Debug)StringConvertible conformance is supposed to be relied on for is developer convenience.  Apple expects anything to be presented to users to go through some localizable mechanism.  I don’t see why we shouldn’t optimize that conformance for development convenience.

**Comment by kyouko-taiga** [comment]
The objection stems from the fact that we can't build a system that relies on exceptions throwing to report errors. You can add your newline to make the emacs experience better, but this hack cannot be relied upon to write the test architecture. A comprehensive solution _must_ call XCTest.report.

**Comment by dabrahams** [comment]
OK, I'll figure out how to make sure that happens.
