### ISSUE TITLE
A better approach to test transpilation?

### ISSUE THREAD

**Issue by kyouko-taiga** [val-lang/val#356]
In the tests for the transpiler, I've noticed that most tests just have a `! cpp` and optionally a `! h` annotation at the top of the file and then just plain Val code. Here's an example:

```swift
/*! h
    Int returns_value();
 */
/*! cpp
    Int returns_value() {
    return 13;
    }
 */
public fun returns_value() -> Int {
  return 13
}
```

My goal with the test annotations was to get them as close as possible to the Val code under test, just like with [FileCheck](https://llvm.org/docs/CommandGuide/FileCheck.html). However, this goal appears to have been missed if I look at the standard practice in our tests. A striking example is [DoWhileStmt.val](https://github.com/val-lang/val/blob/299588199661e22d78a80a213325e4852146b7ab/Tests/ValTests/TestCases/CXX/Stmt/DoWhileStmt.val).

I think one issue is that the framework pushes you to write entire functions inside a single annotation. This is obviously not the granularity level that we'd like.

I have an idea to solve this problem. Rather than having annotations represent a single entity to check, we could concatenate their contents over multiple lines. The result would represent the string to be matched in the transpiled file.

```swift
//! h Int returns_value();
//! cpp Int returns_value() {
public fun returns_value() -> Int {
  //! cpp return 13;
  return 13
}
//! cpp }
```

One problem with this approach, however, is that there's no hard guarantee on the order in which declarations appear in the transpiled file. We could tackle this problem with another annotation.

```swift
//! h Int returns_value();
//! cpp-start returns_value
//! cpp Int returns_value() {
public fun returns_value() -> Int {
  //! cpp return 13;
  return 13
}
//! cpp }
//! cpp-end returns_value
```

**Comment by lucteo** [comment]
I think that would work ok.

My concern is that the test becomes harder to read. I find the first code snippet more readable than the last one.
However the code snippet in the middle looks better, and I can try to write tests in this style.

**Comment by kyouko-taiga** [comment]
We don't have to go through with this change. It's just an idea.

The main problem is the order in which declarations will show up. I can't think of a nice solution to deal with it.

**Comment by dabrahams** [comment]
It's not even clear to me whether it's a good idea to put the inputs and expected output in the same file.  Maybe we should make special line-identifying comment markers where checking a correspondence matters.  But it's probably premature to decide any of this before we have a much larger body of tests, so I think we should let this one percolate.

**Comment by kyouko-taiga** [comment]
No longer relevant.
