### ISSUE TITLE
'AST.coreModule' should come type checked

### ISSUE THREAD

**Issue by kyouko-taiga** [val-lang/val#386]
`AST.coreModule` should guarantee that the core module is type checked. Type errors in the core module will likely lead to precondition failures down the line anyway.

**Comment by dabrahams** [comment]
Wouldn't that mean we'd have to either type check it again later, or hang on to its type-checking artifacts in AST?

**Comment by kyouko-taiga** [comment]
I just realized that it would mean create a typed program with only the core module in which we'd incorporate additional modules later ... That's bad.

I was thinking a little more ahead, when we'll have a serialized format for modules. That format should contain type-checking artifacts and IR along with the syntax of the code. It's likely we'll have to rethink how typed programs are made at this point, because we'll have to be able to compose type-checked and lowered modules read from disk.

Anyway, it looks like a problem for future Dimi. I'm sure she'll enjoy it.
