### ISSUE TITLE
`corelib`, `stdlib` abbrevs are non-standard.

### ISSUE THREAD

**Issue by dabrahams** [val-lang/val#400]
At the very least, these identifiers should be `coreLib` and `stdLib`, but we do we really need these abbrevs?

**Comment by kyouko-taiga** [comment]
What do you mean by non-standard? Both `corelib` (e.g., [Swift](https://github.com/apple/swift-corelibs-foundation), [Go](https://pkg.go.dev/github.com/jomy10/nootlang/corelib), [C#](https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/botr/corelib.md)) and `stdlib` (e.g., [Swift](https://github.com/apple/swift/tree/main/stdlib), [Kotlin](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/), [Lua](https://github.com/lua-stdlib/lua-stdlib)) are pretty common names.

That being said, I have no objection to use `coreLibrary` and `standardLibrary` **in swift**.

Outside of Swift, I'd like to stay away from this horrendous camelCase convention, meaning that from C++ I'd prefer if we could include/import `val/core` and `val/standard_library`, though frankly I don't think anyone could be puzzled by `#include <val/stdlib.h>`.

**Comment by dabrahams** [comment]
I mean the identifiers don't follow the Swift naming standard.

I don't have a strong opinion about the rest of it.  Happy to work with `snake_case` elsewhere.
