### ISSUE TITLE
Better organize the tests

### ISSUE THREAD

**Issue by kyouko-taiga** [val-lang/val#403]
The arborescence of the `Tests/` directory is starting to look messy. We should probably have one that mirrors `Sources/`.

**Comment by dabrahams** [comment]
I'm not sure; would that improve development?  I get tired of trying to remember which modules different parts are in.  I vote we pick whatever arrangement most aids the flow of development.  If that's mirroring `Sources/`, great.

**Comment by kyouko-taiga** [comment]
> I get tired of trying to remember which modules different parts are in.

Ah? Well, I think we agreed it was a good idea to make these modules. You even worked hard on it.

It's pretty clear to me where everything goes, except for extensions that sometimes augment a type defined in another module. Those are rare AFAICT.

> I vote we pick whatever arrangement most aids the flow of development. If that's mirroring Sources/, great.

The mirror approach makes it easy to locate tests for a particular functionality.

**Comment by dabrahams** [comment]
> Ah? I thought we agreed it was a good idea to make these modules. You even worked hard on it.

Yes, that's a separate question.

> The mirror approach makes it easy to locate tests for a particular functionality.

I'm not as sure as you are, but I'm also fine with it.

**Comment by kyouko-taiga** [comment]
Let's move the discussion to #436
