### ISSUE TITLE
The system that copies Val test files into a resource directory breaks workflow

### ISSUE THREAD

**Issue by dabrahams** [val-lang/val#429]
There are two related problems here:

1. If a test fails and you realize you need to update the test case, the diagnostics are pointing to a COPY of the actual Val source file, which you will uselessly try to edit.
2. They copy is not read-only, so I can go ahead and edit it.  And it will cause tests to pass!  And the change will never get checked in!

**Comment by kyouko-taiga** [comment]
The copy is read-only on my setup but the first issue is very real. A quick workaround would be to substitute the prefix of the bundles files by the path to your working directory before the issue gets reported to XCTest using an environment variable.
