### ISSUE TITLE
Create a Windows developer workflow story

### ISSUE THREAD

**Issue by camio** [val-lang/val#45]
The `README.md` instructions aren't sufficient to build Val on a Windows environment. It would be useful to support this environment to increase the pool of Val developers and confirm cross-platform support for the compiler and, eventually, standard libraries. This ticket is intended to track work towards this end.

Here are a few suggestions for getting started:

1. Decide on a Windows package manager for pulling in the Swift and libc++ dependencies. I'd suggest [Chocolatey](https://chocolatey.org/) as this seems to have the largest community at the moment.
2. Create a package for the Windows Swift installer available [here](https://www.swift.org/download/). Contribute this package to the community so it is widely available.
3. Build libc++ on Windows using clang+llvm following instructions available [here](https://libcxx.llvm.org/BuildingLibcxx.html).
4. Create a package for libc++ on Windows.
5. Troubleshoot and fix any issues that arise from running the `swift .build/checkouts/LLVMSwift/utils/make-pkgconfig.swift` command per the instructions.
6. Troubleshoot and fix any issues with building the compiler.
7. Update the `README.md` to indicate Windows support and provide its workflow.

**Comment by kyouko-taiga** [comment]
A lot of progress has been made on that front. The README should be updated accordingly.
