### ISSUE TITLE
Replace handwritten ASTs

### ISSUE THREAD

**Issue by kyouko-taiga** [val-lang/val#47]
Most programs used to test the type checker use a programmatically built AST (e.g., [TypeCheckerTests.testTraitDecl](https://github.com/val-lang/val/blob/5a35a28556d636bfb221a0c99d5b36fcdd4aefbf/Tests/ValTests/TypeCheckerTests.swift#L6)). That makes test cases hard to read, update, and maintain.

It would be preferable if those test cases generated ASTs from actual Val code using the parser.

**Comment by kyouko-taiga** [comment]
Here is an example of how to do it: https://github.com/val-lang/val/blob/b886b7bfa14e8ecb711f326a8003a0f7f37c17b9/Tests/ValTests/TypeCheckerTests.swift#L2033-L2042

**Comment by dan-zheng** [comment]
I can give this a stab this week (forking the `stdlib` branch), unless someone would like to make faster progress!

**Comment by kyouko-taiga** [comment]
That would be amazing!

**Comment by kyouko-taiga** [comment]
Done with [#b978e20](https://github.com/val-lang/val/commit/b978e208cbe4ccd2452c010489dfcd83be2ecad0)
