### ISSUE TITLE
Shadow/discard memberwise initializers

### ISSUE THREAD

**Issue by kyouko-taiga** [val-lang/val#503]
The memberwise initializer of a type should be shadowed/discarded if there exists a custom initializer with the same signature. For example:

```swift
type A {
  let x: Int
  init(x: Int) { &self.x = x + 1 }
}
```

**Comment by dabrahams** [comment]
I almost wonder if that initializer should be allowed.  I can't think of a good rule to disallow it, but making something that looks just like a memberwise initializer but has different semantics seems dodgy at least.
