### ISSUE TITLE
Bool negation doesn't work in end-to-end test

### ISSUE THREAD

**Issue by lucteo** [val-lang/val#510]
@kyouko-taiga : for some reason, Bool negation doesn't work. I'll leave it like that for now, and we can go back to it later.

_Originally posted by @lucteo in https://github.com/val-lang/val/pull/509#discussion_r1133115978_

**Comment by kyouko-taiga** [comment]
It's because the operator isn't implemented yet. See `Bool.val` in the core library.

**Comment by lucteo** [comment]
Please note that in the patch I've noticed this problem, I've also added in Bool.val:
```
  /// Returns negation of `self`.
  public fun prefix! () -> Bool {
    Bool(value: Builtin.icmp_eq_i1(value, Builtin.zeroinitializer_i1()))
  }
```

**Comment by kyouko-taiga** [comment]
Okay, I will investigate.

**Comment by kyouko-taiga** [comment]
The type checker can process `!x` with your definition.
What's the error you're hitting? Is is in the IR emitter?
