### ISSUE TITLE
On the implementation of subscripts

### ISSUE THREAD

**Issue by kyouko-taiga** [val-lang/val#571]
## A simple mental model

There's a simple mental model I like for explaining projections: a subscript is a function that calls another function on the projected value. For example, these two programs have equivalent semantics:

```swift
// 1
subscript incremented(_ x: Int): Int { let y = x + 1; yield y }
public fun main() {
  let s = 10
  let t = incremented[s] 
  print(t)
}

// 2
fun with_incremented<E,T>(_ x: Int, _ c: [E](Int) -> T) -> T { let y = x + 1; c(y) }
public fun main() {
  let s = 10
  with_incremented(s, fun(t) { print(t) })
}
```

## The problem of arbitrary overlapping projections

Unfortunately, this simple model can only work when overlapping projections nest. Consider this:

```swift
subscript f(_ x: Int): Int { x }
public fun main() {
  let s = 10
  let t = f[s] // <--|
  let u = f[s] // <--+--|
  print(t)     // <--|  |
  print(u)     // <-----|
}
```

Here, neither the lifetime of `t` nor that of `u` is nested into the other. So we can't naively wrap the code within the lifetime of either into a lambda.

## Eager continuations

At CppCon, @dabrahams suggested that we created continuations that wrap the whole code after the start of a projection, regardless of the end of its lifetime. The idea was that if we could already convince ourselves that value uniqueness was upheld, then it wouldn't matter what low-level code we generate.

This technique would work in the above example, but only because everything is immutable. I think that's because logically extending the lifetime of `t` so that it encapsulates that of `u` doesn't change the behavior of the program outside of what the specification allows. Indeed, Val only guarantees that a projection ends _after_ its last use, but not necessarily as soon as possible.

But the same approach can't apply in the presence of mutation:

```swift
subscript f(_ x: yielded Int): Int { let { x } inout { &x } }
public fun main() {
  var s = 10
  inout t = f[&s]
  &t += 1
  print(s)
}
```

This program is obviously legal. But if we capture all the code after the binding of `t` in a lambda, then its lifetime will cover that of the immutable use of `s`. One may think that it's not an issue, since we'd have already established that the program is legal before the transformation, but consider this:

```swift
subscript f(_ x: yielded Int): Int {
  let { x }
  inout { var y = x; yield &y; x = y }
}
```

The above subscript is moving the value of the projected value out of its storage. That should be fine, because we should be allowed to rely on the guarantee that no one will try to read `x` before control returns. but the transformation is going against this assumption.

### Falsy hope

At CppCon, I thought we could deal with this situation by only eagerly wrap code into continuations of immutable projections. For mutable projections, we would only wrap code within a binding's useful lifetime, essentially falling back on my simpler mental model. I though it would work because overlapping mutable projections must nest, unlike immutable ones.

Unfortunately, I overlooked this situation:

```swift
subscript f(_ x: yielded Int): Int { let { x } inout { &x } }
public fun main() {
  var s = 10
  let t = f[s]
  if t > Int.random(in: 0 ..< 100) {
    inout u = f[&s]
    &u += 1
  } else {
    print(t)
  }
}
```

The problem here is that there isn't a single point where we can decide to terminate the projection of `t`. Its useful lifetime ends in both branches of the conditional statement. Further, we can't extend it until after the conditional because we need `s` to be unique by the time we bind `u`.

## A page from co-routines

I originally thought we could implement subscripts like co-routines. A subscript would be compiled to two functions. The first would implement the code before `yield` and return a pointer to the projected value along with an environment and a tag identifying where it gave away control. The second would implement the code after `yield`.

Roughly speaking, it would look like the following:
```swift
// 1
subscript truthy(x: Int): Bool {
  var s = "was "
  if x == 0 {
    yield false
    print(s + "falsy")
  } else {
    yield true
    print(s + "truthy")
  }
}

// 2
fun truthy_before(x: Int) -> {Pointer<Bool>, Pointer<{String, Bool}>, Int} {
  let e = MutablePointer<{String, Bool}>.allocate(count: 1)
  let s = e.rebound<String>()
  unsafe s.initialize(to: "was")
  let b = e.advanced(by: MemoryLayout<String>.size).rebound<Bool>()
  if x == 0 {
    unsafe b.initialize(to: false)
    return (b, e, 0)
  } else {
    unsafe b.initialize(to: true)
    return (b, e, 1)
  }
}

fun truthy_after(_ e: Pointer<{String, Bool}>, tag: Int) -> Void {
  match tag {
    0 { print(unsafe e.rebound<String>.pointee + "falsy") }
    1 { print(unsafe e.rebound<String>.pointee + "truthy") }
  }
  unsafe e.deinitialize()
  unsafe e.deallocate()
}
```

The problem with that approach is that it involves dynamic allocation, meaning that subscripts would no longer a be zero-cost abstraction feature. But I think I have a solution.

### Truthy hope?

The dynamic allocation is used to store the objects that are projected or created before `yield` and used after. Since we're only talking about object storage, then, I think we can statically determine the size we need. It doesn't matter how many functions are called before or after `yield`, so we don't need to allocate a call stack, only a single frame.

So we could ask the subscript's caller to allocate such storage within its own  frame. For instance, in the above example, `truthy_before` and `truthy_after` would use a block of memory passed from the caller as their local stack and dynamic allocation would no longer be necessary.

It's not necessarily easy to determine the exact minimum storage we need during lowering because we can't know whether a local binding requires storage before we run last use analysis, but we can definitely get an upper bound. That's probably good enough for the vast majority of cases.

Another limitation is that subscripts would not be allowed to use something like `alloca`. I think this is pretty minor, though, because they would still be allowed to call functions that do it.

**Comment by dabrahams** [comment]
Your pointer manipulations in `truthy_before` would produce UB if the usual rules apply to val (b doesn't point at the bool in the tuple).  Can you come up with an example that only uses safe operations?

**Comment by kyouko-taiga** [comment]
Not sure it's possible with only safe operations. However, I took some shortcuts to keep the example concise and because we have yet to finalize the actual API of pointers for Val. So to hopefully makes tings clearer, here's what I meant in Swift:

```swift
func truthy_before(x: Int) -> (UnsafeMutablePointer<Bool>, UnsafeMutableRawPointer, Int) {
  let e = UnsafeMutableRawPointer.allocate(
    byteCount: MemoryLayout<(String, Bool)>.size,
    alignment: MemoryLayout<(String, Bool)>.alignment)
  let s = e.assumingMemoryBound(to: String.self)
  s.initialize(to: "was ")

  let b = e
    .advanced(by: MemoryLayout<(String, Bool)>.offset(of: \.1)!)
    .assumingMemoryBound(to: Bool.self)
  if x == 0 {
    b.initialize(to: false)
    return (b, e, 0)
  } else {
    b.initialize(to: true)
    return (b, e, 1)
  }
}
```

**Comment by dabrahams** [comment]
Resolved in slack.  The part missing from Dimi's rendition of my CppCon suggestion was that the projection code after the yield, which ends the lifetime of the projection, is passed as a closure to the continuation passed into the projection along with the let/inout-bound projected value, and the continuation calls that closure when the lifetime of the projection ends.  (@kyouko-taiga please verify and close if appropriate)

**Comment by kyouko-taiga** [comment]
**Summary of a chat with Dave about that:**

There's a way to work around the issue I mentioned about eager continuations. Rather than simply calling a continuation with the projected value, a subscript could also pass a callback. The continuation will be expected to call it when it's done with the projection.

For example:
```swift
// 1
subscript truthy(x: Int): Bool {
  var s = "was "
  if x == 0 {
    yield false
    print(s + "falsy")
  } else {
    yield true
    print(s + "truthy")
  }
}

// 2
fun truthy<E, T>(x: Int, c: [E](Bool, [Pointer<Frame>]() -> Void) -> T) -> T {
  var s = "was "
  if x == 0 {
    return c(false, fun() { print(s + "falsy") })
  } else {
    return c(true, fun() { print(s + "truthy") })
  }
}
```
In (2), `truthy` expects `c` to eventually call the lambda that gets passed as its second argument.

One big advantage of this solution over the one I suggested is that supports ABI stability. If the caller of a subscript needs to know how much memory it has to allocate before calling it, then it means we can't modify the implementation of a subscript without having all its callers being recompiled too (note: a workaround could be to have a symbol next to each subscript that tells what size the caller is expected to allocate).
