### ISSUE TITLE
Incorrect instructions for building

### ISSUE THREAD

**Issue by dabrahams** [val-lang/val#594]
We need to include the correct instructions for Swifty-LLVM (which are [currently wrong](https://github.com/val-lang/Swifty-LLVM/issues/17))

**Comment by adaszko** [comment]
Hi!  This is related enough to not open a separate issue.  I succeeded in building `valc` with a homebrew-installed llvm, which I think is what most people use.  It would be nice to put this in one form or another into README:

```
$ git clone https://github.com/val-lang/Swifty-LLVM.git
$ cd Swifty-LLVM
$ brew install llvm@15
$ ./Tools/make-pkgconfig.sh llvm.pc
$ cd ..
$ git clone https://github.com/val-lang/val.git
$ cd val
$ cp ../Swifty-LLVM/llvm.pc ./
$ export PKG_CONFIG_PATH=$PWD
$ swift build -c release
```

Produces `valc` at `.build/arm64-apple-macosx/release/valc`

Just for reference, here’s my `llvm.pc`:
```
Name: LLVM
Description: Low-level Virtual Machine compiler framework
Version: 15.0.7
URL: http://www.llvm.org/
Libs: -lc++ -L/opt/homebrew/Cellar/llvm@15/15.0.7/lib -lLLVM-15
Cflags: -I/opt/homebrew/Cellar/llvm@15/15.0.7/include
```

**Comment by dabrahams** [comment]
Good idea, @adaszko. It's nice to have the option not to put the .pc file in some system path.  I didn't want to have to set an environment variable, and wanted to have the option to use XCode, so mine is in `$HOMEBREW_PREFIX/lib/pkgconfig`, which we should also list as an option.

**Comment by dabrahams** [comment]
@adaszko you inspired [this change](https://github.com/val-lang/val/pull/604/commits/faeb71d91603417ce942fcb7cc6c1f67035b0948#diff-bc668a2c9f2299cef15b222055b4b4d5311646caec2e7610e540cee18ae9b948L87-L95), getting sudo out of our CI process.

**Comment by adaszko** [comment]
> @adaszko you inspired [this change](https://github.com/val-lang/val/pull/604/commits/faeb71d91603417ce942fcb7cc6c1f67035b0948#diff-bc668a2c9f2299cef15b222055b4b4d5311646caec2e7610e540cee18ae9b948L87-L95), getting sudo out of our CI process.

Great.  Now I wish I’d inspire something high impact, like a type system improvement for example 😄

**Comment by kyouko-taiga** [comment]
> Great. Now I wish I’d inspire something high impact, like a type system improvement for example 😄

That's not out of reach.
Do you have any idea? 😉
