### ISSUE TITLE
"is not representable in LLVM" assertion

### ISSUE THREAD

**Issue by dabrahams** [val-lang/val#677]
With `--import-builtin`, this file makes the compiler assert, with

CodeGenLLVM/LoweredProgram+Extensions.swift:152: Fatal error: 'Pointee' is not representable in LLVM

```
type Pointer<Pointee> {

  var base: Builtin.ptr

  memberwise init

  public property q: Pointee {
    yield base as* (remote let Pointee)
  }
}

fun test(p: Pointer<Int>) {
  var x: Int = p.q // Actual problem: var should be let
}

public fun main() {}
```

**Comment by kyouko-taiga** [comment]
The problem seems to be that `p.q` is inferred as having type `Pointee` instead of `Int`. I'm almost certain the issue comes from `TypeChecker.inferredType(of:shapedBy:updating:)` (the overload for `SubscriptCallExpr`).
