### ISSUE TITLE
Use less confusing floating-point type names

### ISSUE THREAD

**Issue by kyouko-taiga** [val-lang/val#694]
General purpose floating-point numbers should be represented by `Float` instead of `Double`, which would represent a "machine-size" floating-point number. Floating-point numbers with specific bit widths should be represented by `Float16`, `Float32`, `Float64` and `Float128`.

**Comment by peter-evans** [comment]
Does this mean that Hylo won't have a `Double` type and the examples in the language tour should be updated to `Float64`? Or is the intention to alias `Double` to `Float64` in future?

Sorry if this is dumb question. I'm interested in Hylo and trying to learn. 😅

**Comment by kyouko-taiga** [comment]
There are no dumb questions! Thanks for asking.

We're planning to use `Float64` instead of `Double` for the foreseeable future and so the examples in the tour, which are all very outdated, must be modified.
