### ISSUE TITLE
Remove the dependency on an environment variable for running tests!

### ISSUE THREAD

**Issue by dabrahams** [val-lang/val#7]
> /Users/dave/src/val/Sources/Driver/Driver.swift:110: error: -[ValTests.ValTests testEval] : failed: caught error: "moduleNotFound(moduleName: "Val")"

Seems like this indicates something might need to go into "/opt/local/lib/val"?  Just guessing here.

**Comment by kyouko-taiga** [comment]
Tests have no dependencies that are not built with Swift PM, but they need one environment variable (see https://github.com/val-lang/val#run-the-tests).

**Comment by kyouko-taiga** [comment]
Fixed in 7e104cb
