### ISSUE TITLE
Unexpected failures in CXX tests (parsing, typechecking) need to dump the actual diagnostics

### ISSUE THREAD

**Issue by dabrahams** [val-lang/val#74]
These failures: https://github.com/val-lang/val/blob/96eb07bf89fbb9e92fe0147728562e787df5be7e/Tests/ValTests/CXXTests.swift#L39
https://github.com/val-lang/val/blob/96eb07bf89fbb9e92fe0147728562e787df5be7e/Tests/ValTests/CXXTests.swift#L46

Need to pass the file and line of the test cases to the `file:` and `line:` XCTAssert parameters, and pass the text of the diagnostics to as the `message` parameter.

Diagnostic logging looks really complicated to me and it appears to be coupled into the CLI, so I don't know how to do this job.  But without it, test development is going to be really painful.

**Comment by dabrahams** [comment]
It's not interpreting that I'm concerned about; it's getting the string representation.

**Comment by kyouko-taiga** [comment]
Then `Diagnostic.message` is all you need.
