### ISSUE TITLE
CI fails on Ubuntu

### ISSUE THREAD

**Issue by kyouko-taiga** [val-lang/val#801]
See https://github.com/val-lang/val/actions/runs/5686848323/job/15414347501#step:5:1209 (updated link)

According to Internet wisdom the problem seems to be related with the fact that we're trying to run commands in a non-interactive terminal. I tried to pass `-t` to `docker run` unsuccessfully.

**Comment by hypdeb** [comment]
This seems to be what kills it right ?
```
  /workspaces/val/.build/checkouts/Swifty-LLVM/Sources/llvmshims/src/shim.cc:1:10: fatal error: 'llvm-c/TargetMachine.h' file not found
  #include "llvm-c/TargetMachine.h"
           ^~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
```
How does it relate to the non-interactive terminal issue you mention ?

**Comment by kyouko-taiga** [comment]
Sorry, look at this one: https://github.com/val-lang/val/actions/runs/5686848323/job/15414347501#step:5:1209
