### ISSUE TITLE
Synthesize default access modifiers

### ISSUE THREAD

**Issue by kyouko-taiga** [val-lang/val#84]
Add a default access modifier (likely `private`) and synthesize it on all declaration when `public` is not explicitly supplied.

**Comment by nickpdemarco** [comment]
I'm taking a look at this - can you clarify which declarations should have a synthesized `private`? I'm assuming things like import and namespace declarations don't make sense to label as private.

**Comment by kyouko-taiga** [comment]
The idea is that all declarations that currently have an optional access modifier property, like `FunctionDecl`, `SubscriptDecl`, etc., should have a non-optional property instead, replacing the `nil` cases by a synthesized `private` modifier.
